#!/usr/bin/env python3

# Resource agent for qemu COLO for use with Pacemaker CRM
#
# Copyright (c) Lukas Straub <lukasstraub2@web.de>
#
# This work is licensed under the terms of the GNU GPL, version 2 or
# later.  See the COPYING file in the top-level directory.

import subprocess
import sys
import os
import os.path
import signal
import socket
import select
import json
import re
import time
import logging
import logging.handlers
import traceback

# Constants
OCF_SUCCESS = 0
OCF_ERR_GENERIC = 1
OCF_ERR_ARGS = 2
OCF_ERR_UNIMPLEMENTED = 3
OCF_ERR_PERM = 4
OCF_ERR_INSTALLED = 5
OCF_ERR_CONFIGURED = 6
OCF_NOT_RUNNING = 7
OCF_RUNNING_MASTER = 8
OCF_FAILED_MASTER = 9

# Get environment variables
OCF_RESKEY_CRM_meta_notify_type = os.getenv("OCF_RESKEY_CRM_meta_notify_type")
OCF_RESKEY_CRM_meta_notify_operation = os.getenv("OCF_RESKEY_CRM_meta_notify_operation")
OCF_RESKEY_CRM_meta_notify_key_operation = os.getenv("OCF_RESKEY_CRM_meta_notify_key_operation")
OCF_RESKEY_CRM_meta_notify_start_uname = os.getenv("OCF_RESKEY_CRM_meta_notify_start_uname", "")
OCF_RESKEY_CRM_meta_notify_stop_uname = os.getenv("OCF_RESKEY_CRM_meta_notify_stop_uname", "")
OCF_RESKEY_CRM_meta_notify_active_uname = os.getenv("OCF_RESKEY_CRM_meta_notify_active_uname", "")
OCF_RESKEY_CRM_meta_notify_promote_uname = os.getenv("OCF_RESKEY_CRM_meta_notify_promote_uname", "")
OCF_RESKEY_CRM_meta_notify_demote_uname = os.getenv("OCF_RESKEY_CRM_meta_notify_demote_uname", "")
OCF_RESKEY_CRM_meta_notify_master_uname = os.getenv("OCF_RESKEY_CRM_meta_notify_master_uname", "")
OCF_RESKEY_CRM_meta_notify_slave_uname = os.getenv("OCF_RESKEY_CRM_meta_notify_slave_uname", "")

HA_RSCTMP = os.getenv("HA_RSCTMP", "/run/resource-agents")
HA_LOGFACILITY = os.getenv("HA_LOGFACILITY")
HA_LOGFILE = os.getenv("HA_LOGFILE")
HA_DEBUG = os.getenv("HA_debug", "0")
HA_DEBUGLOG = os.getenv("HA_DEBUGLOG")
OCF_RESOURCE_INSTANCE = os.getenv("OCF_RESOURCE_INSTANCE", "default-instance")
OCF_RESKEY_CRM_meta_timeout = int(os.getenv("OCF_RESKEY_CRM_meta_timeout", "40000"))
OCF_RESKEY_CRM_meta_interval = int(os.getenv("OCF_RESKEY_CRM_meta_interval", "1"))
OCF_RESKEY_CRM_meta_clone_max = int(os.getenv("OCF_RESKEY_CRM_meta_clone_max", "1"))
OCF_RESKEY_CRM_meta_clone_node_max = int(os.getenv("OCF_RESKEY_CRM_meta_clone_node_max", "1"))
OCF_RESKEY_CRM_meta_master_max = int(os.getenv("OCF_RESKEY_CRM_meta_master_max", "1"))
OCF_RESKEY_CRM_meta_master_node_max = int(os.getenv("OCF_RESKEY_CRM_meta_master_node_max", "1"))
OCF_RESKEY_CRM_meta_notify = os.getenv("OCF_RESKEY_CRM_meta_notify")
OCF_RESKEY_CRM_meta_globally_unique = os.getenv("OCF_RESKEY_CRM_meta_globally_unique")

HOSTNAME = os.getenv("OCF_RESKEY_CRM_meta_on_node", socket.gethostname())

OCF_ACTION = os.getenv("__OCF_ACTION")
if not OCF_ACTION and len(sys.argv) == 2:
    OCF_ACTION = sys.argv[1]

# Resource parameters
OCF_RESKEY_qemu_binary_default = "qemu-system-x86_64"
OCF_RESKEY_colod_binary_default = "colod"
OCF_RESKEY_qemu_img_binary_default = "qemu-img"
OCF_RESKEY_log_dir_default = HA_RSCTMP
OCF_RESKEY_options_default = ""
OCF_RESKEY_active_hidden_dir_default = ""
OCF_RESKEY_advanced_config_default = "{}"
OCF_RESKEY_listen_address_default = "0.0.0.0"
OCF_RESKEY_host_map_default = "{}"
OCF_RESKEY_base_port_default = "9000"
OCF_RESKEY_monitor_interface_default = ""
OCF_RESKEY_low_yank_timeout_default = "1000"
OCF_RESKEY_high_yank_timeout_default = "20000"
OCF_RESKEY_debug_default = "0"

OCF_RESKEY_qemu_binary = os.getenv("OCF_RESKEY_qemu_binary", OCF_RESKEY_qemu_binary_default)
OCF_RESKEY_colod_binary = os.getenv("OCF_RESKEY_colod_binary", OCF_RESKEY_colod_binary_default)
OCF_RESKEY_qemu_img_binary = os.getenv("OCF_RESKEY_qemu_img_binary", OCF_RESKEY_qemu_img_binary_default)
OCF_RESKEY_log_dir = os.getenv("OCF_RESKEY_log_dir", OCF_RESKEY_log_dir_default)
OCF_RESKEY_options = os.getenv("OCF_RESKEY_options", OCF_RESKEY_options_default)
OCF_RESKEY_active_hidden_dir = os.getenv("OCF_RESKEY_active_hidden_dir", OCF_RESKEY_active_hidden_dir_default)
OCF_RESKEY_advanced_config = os.getenv("OCF_RESKEY_advanced_config", OCF_RESKEY_advanced_config_default)
OCF_RESKEY_listen_address = os.getenv("OCF_RESKEY_listen_address", OCF_RESKEY_listen_address_default)
OCF_RESKEY_host_map = os.getenv("OCF_RESKEY_host_map", OCF_RESKEY_host_map_default)
OCF_RESKEY_base_port = os.getenv("OCF_RESKEY_base_port", OCF_RESKEY_base_port_default)
OCF_RESKEY_monitor_interface = os.getenv("OCF_RESKEY_monitor_interface", OCF_RESKEY_monitor_interface_default)
OCF_RESKEY_low_yank_timeout = os.getenv("OCF_RESKEY_low_yank_timeout", OCF_RESKEY_low_yank_timeout_default)
OCF_RESKEY_high_yank_timeout = os.getenv("OCF_RESKEY_high_yank_timeout", OCF_RESKEY_high_yank_timeout_default)
OCF_RESKEY_debug = os.getenv("OCF_RESKEY_debug", OCF_RESKEY_debug_default)

BASE_DIR = os.path.join(HA_RSCTMP, OCF_RESOURCE_INSTANCE)
HELPER_SOCK = os.path.join(BASE_DIR, "colod.sock")

COLOD_PIDFILE = os.path.join(BASE_DIR, "colod.pid")

QMP_LOG = os.path.join(OCF_RESKEY_log_dir, OCF_RESOURCE_INSTANCE + "-qmp.log")
HELPER_LOG = os.path.join(OCF_RESKEY_log_dir, OCF_RESOURCE_INSTANCE + "-helper.log")

START_TIME = time.time()

# Exception only raised by ourself
class Error(Exception):
    pass

def colod_cmdline():
    cmdline = [OCF_RESKEY_colod_binary, "--daemonize", "--syslog",
        "--instance_name", OCF_RESOURCE_INSTANCE, "--node_name", HOSTNAME,
        "--base_directory", BASE_DIR,
        "--qemu", OCF_RESKEY_qemu_binary,"--qemu_img", OCF_RESKEY_qemu_img_binary,
        "--timeout_low", OCF_RESKEY_low_yank_timeout,
        "--timeout_high", OCF_RESKEY_high_yank_timeout,
        "--command_timeout", str(OCF_RESKEY_CRM_meta_timeout - 10*1000),
        "--watchdog_interval", "500", "--listen_address", OCF_RESKEY_listen_address,
        "--base_port", OCF_RESKEY_base_port, "--active_hidden_dir", OCF_RESKEY_active_hidden_dir,
        "--advanced_config", OCF_RESKEY_advanced_config, "--qemu_options", OCF_RESKEY_options,
        "--host_map", OCF_RESKEY_host_map]

    if int(OCF_RESKEY_debug) >= 1:
        cmdline = cmdline + ["--trace"]

    if OCF_RESKEY_monitor_interface:
        cmdline = cmdline + ["--monitor_interface", OCF_RESKEY_monitor_interface]

    return cmdline

def qemu_colo_meta_data():
    print("""\
<?xml version="1.0"?>
<!DOCTYPE resource-agent SYSTEM "ra-api-1.dtd">
<resource-agent name="colo">

    <version>1.0</version>
    <longdesc lang="en">
Resource agent for qemu COLO. (https://wiki.qemu.org/Features/COLO)

After defining the master/slave instance, the master score has to be
manually set to show which node has up-to-date data. So you copy your
image to one host (and create empty images the other host(s)) and then
run "crm_master -r name_of_your_primitive -v 10" on that host.
Also, you have to set 'notify=true' in the metadata attributes when
defining the primary/secondary instance.

Note:
-If the instance is stopped cluster-wide, the resource agent will do a
clean shutdown. Set the demote timeout to the time it takes for your
guest to shutdown.
-The resource agent may notify pacemaker about peer failure,
these failures will show up with exitreason="Simulated failure".
    </longdesc>
    <shortdesc lang="en">Qemu COLO</shortdesc>

    <parameters>

    <parameter name="qemu_binary" unique="0" required="0">
        <longdesc lang="en">qemu binary to use</longdesc>
        <shortdesc lang="en">qemu binary</shortdesc>
        <content type="string" default=\"""" + OCF_RESKEY_qemu_binary_default + """\"/>
    </parameter>

    <parameter name="colod_binary" unique="0" required="0">
        <longdesc lang="en">colod binary to use</longdesc>
        <shortdesc lang="en">colod binary</shortdesc>
        <content type="string" default=\"""" + OCF_RESKEY_colod_binary_default + """\"/>
    </parameter>

    <parameter name="qemu_img_binary" unique="0" required="0">
        <longdesc lang="en">qemu-img binary to use</longdesc>
        <shortdesc lang="en">qemu-img binary</shortdesc>
        <content type="string" default=\"""" + OCF_RESKEY_qemu_img_binary_default + """\"/>
    </parameter>

    <parameter name="log_dir" unique="0" required="0">
        <longdesc lang="en">Directory to place logs in</longdesc>
        <shortdesc lang="en">Log directory</shortdesc>
        <content type="string" default=\"""" + OCF_RESKEY_log_dir_default + """\"/>
    </parameter>

    <parameter name="options" unique="0" required="0">
        <longdesc lang="en">
Options to pass to qemu. These will be passed alongside COLO specific
options, so you need to follow these conventions: The netdev should have
id=hn0 and the disk controller drive=colo-disk0. The image node should
have node-name=parent0, but should not be connected to the guest.
Example:
-vnc :0 -enable-kvm -cpu qemu64,+kvmclock -m 512 -netdev bridge,id=hn0
-device e1000,netdev=hn0 -device virtio-blk,drive=colo-disk0
-drive if=none,node-name=parent0,format=qcow2,file=/mnt/vms/vm01.qcow2
        </longdesc>
        <shortdesc lang="en">Options to pass to qemu.</shortdesc>
    </parameter>

    <parameter name="active_hidden_dir" unique="0" required="1">
        <longdesc lang="en">
Directory where the active and hidden images will be stored. It is
recommended to put this on a ramdisk.
        </longdesc>
        <shortdesc lang="en">Path to active and hidden images</shortdesc>
        <content type="string" default=\"""" + OCF_RESKEY_active_hidden_dir_default + """\"/>
    </parameter>

    <parameter name="advanced_config" unique="0" required="0">
        <shortdesc lang="en">Advanced config options</shortdesc>
        <longdesc lang="en">
Json object containing advanced configuration options.

If the object contains a "include" member, it's value is parsed as a
file name. The file is parsed as a json object which is then updated
with values of the current object e.g. values of the current object
take precedence over the values of the included object.
The file may contain another "include" member, which is parsed
recursively.

If "qemu-options-str" is configured here, it takes precedence over the
"options" parameter to the resource-agent.
"qemu-options-str" may be a list of strings, which will be concatenated.

Consult the qemu qmp documentation for more information at
https://www.qemu.org/docs/master/interop/qemu-qmp-ref.html

Example using a config file:
    advanced_config='{"include": "/etc/debian_vm.json"}'

/etc/debian_vm.json:
{
    "qemu-options-str": [
        " -vnc :0 -enable-kvm -cpu qemu64,+kvmclock -m 2048",
        " -netdev bridge,id=hn0 -device e1000,netdev=hn0",
        " -device virtio-blk,drive=colo-disk0",
        " -drive if=none,node-name=parent0,format=qcow2,",
        "file=/mnt/vms/debian_vm.qcow2"
    ],
    "vnet-hdr": false,
    "filter-rewriter": true,
    "colo-compare-options": {"expired_scan_cycle": 100},
    "migration-parameters": {"multifd-channels": 4},
    "migration-capabilities": [{"capability": "multifd", "state": true}],
    "throttle-limits": {"bps-read": 104857600, "bps-write": 104857600}
}
        </longdesc>
        <content type="string" default=\"""" + OCF_RESKEY_advanced_config_default + """\"/>
    </parameter>

    <parameter name="listen_address" unique="0" required="0">
        <longdesc lang="en">Address to listen on.</longdesc>
        <shortdesc lang="en">Listen address</shortdesc>
        <content type="string" default=\"""" + OCF_RESKEY_listen_address_default + """\"/>
    </parameter>

    <parameter name="host_map" unique="0" required="0">
        <longdesc lang="en">
Map each host to a ip address to use for replication. Must be a valid json object.
Example:
{"node1": "192.168.222.10", "node2": "192.168.222.11"}
        </longdesc>
        <shortdesc lang="en">Host map</shortdesc>
        <content type="string" default=\"""" + OCF_RESKEY_host_map_default + """\"/>
    </parameter>

    <parameter name="base_port" unique="1" required="0">
        <longdesc lang="en">
4 tcp ports that are unique for each instance. (base_port to base_port + 3)
        </longdesc>
        <shortdesc lang="en">Ports to use</shortdesc>
        <content type="integer" default=\"""" + OCF_RESKEY_base_port_default + """\"/>
    </parameter>

    <parameter name="monitor_interface" unique="0" required="0">
        <longdesc lang="en">
When this is set and the link goes down on the
primary node, failover to the secondary node.
        </longdesc>
        <shortdesc lang="en">monitor interface</shortdesc>
        <content type="string" default=\"""" + OCF_RESKEY_monitor_interface_default + """\"/>
    </parameter>

    <parameter name="low_yank_timeout" unique="0" required="0">
        <longdesc lang="en">
Timeout for QMP commands after which to execute the "yank" command,
in milliseconds.
Must be lower than any of the action timeouts.
        </longdesc>
        <shortdesc lang="en">Low yank timeout</shortdesc>
        <content type="integer" default=\"""" + OCF_RESKEY_low_yank_timeout_default + """\"/>
    </parameter>

    <parameter name="high_yank_timeout" unique="0" required="0">
        <longdesc lang="en">
Timeout for QMP commands after which to execute the "yank" command,
in milliseconds.
Must be lower than any of the action timeouts.
Used during critical sections where the qemu mainloop will be blocked
longer than usual.
        </longdesc>
        <shortdesc lang="en">High yank timeout</shortdesc>
        <content type="integer" default=\"""" + OCF_RESKEY_high_yank_timeout_default + """\"/>
    </parameter>

    <parameter name="debug" unique="0" required="0">
        <longdesc lang="en">
Control debugging:
0: disable debugging
1: log debug messages and qmp commands
        </longdesc>
        <shortdesc lang="en">Control debugging</shortdesc>
        <content type="integer" default=\"""" + OCF_RESKEY_debug_default + """\"/>
    </parameter>

    </parameters>

    <actions>
        <action name="start"        timeout="75s" />
        <action name="stop"         timeout="75s" />
        <action name="monitor"      timeout="30s" \
            interval="10000ms" depth="0" role="Slave" />
        <action name="monitor"      timeout="30s" \
            interval="10001ms" depth="0" role="Master" />
        <action name="notify"       timeout="30s" />
        <action name="promote"      timeout="75s" />
        <action name="demote"       timeout="75s" />
        <action name="meta-data"    timeout="5s" />
        <action name="validate-all" timeout="30s" />
    </actions>

</resource-agent>
""")

# Sanity checks: check parameters, files, binaries, etc.
def qemu_colo_validate_all():
    # Check resource parameters
    if not str.isdigit(OCF_RESKEY_base_port):
        log.error("base_port needs to be a number")
        return OCF_ERR_CONFIGURED

    if not str.isdigit(OCF_RESKEY_low_yank_timeout):
        log.error("low_yank_timeout needs to be a number")
        return OCF_ERR_CONFIGURED

    if not str.isdigit(OCF_RESKEY_high_yank_timeout):
        log.error("high_yank_timeout needs to be a number")
        return OCF_ERR_CONFIGURED

    if not str.isdigit(OCF_RESKEY_debug):
        log.error("debug needs to be a number")
        return OCF_ERR_CONFIGURED

    if not OCF_RESKEY_active_hidden_dir:
        log.error("active_hidden_dir needs to be specified")
        return OCF_ERR_CONFIGURED

    try:
        config = json.loads(OCF_RESKEY_advanced_config)
    except Exception as e:
        log.error("Failed parsing advanced_config: %s" % str(e))

    try:
        json.loads(OCF_RESKEY_host_map)
    except Exception as e:
        log.error("host_map is not valid json: %s" % str(e))

    # Check resource meta configuration
    if OCF_ACTION != "stop":
        if OCF_RESKEY_CRM_meta_master_max != 1:
            log.error("only one master allowed")
            return OCF_ERR_CONFIGURED

        if OCF_RESKEY_CRM_meta_clone_max > 2:
            log.error("maximum 2 clones allowed")
            return OCF_ERR_CONFIGURED

        if OCF_RESKEY_CRM_meta_master_node_max != 1:
            log.error("only one master per node allowed")
            return OCF_ERR_CONFIGURED

        if OCF_RESKEY_CRM_meta_clone_node_max != 1:
            log.error("only one clone per node allowed")
            return OCF_ERR_CONFIGURED

    # Check if notify is enabled
    if OCF_ACTION != "stop" and OCF_ACTION != "monitor":
        if not is_true(OCF_RESKEY_CRM_meta_notify) \
           and not OCF_RESKEY_CRM_meta_notify_start_uname:
            log.error("notify needs to be enabled")
            return OCF_ERR_CONFIGURED

    # Check that globally-unique is disabled
    if is_true(OCF_RESKEY_CRM_meta_globally_unique):
        log.error("globally-unique needs to be disabled")
        return OCF_ERR_CONFIGURED

    # Check binaries
    if not check_binary(OCF_RESKEY_colod_binary):
        return OCF_ERR_INSTALLED

    # Check paths and files
    if not is_writable(OCF_RESKEY_active_hidden_dir) \
        or not os.path.isdir(OCF_RESKEY_active_hidden_dir):
        log.error("active and hidden image directory missing or not writable")
        return OCF_ERR_PERM

    return OCF_SUCCESS

def logs_open():
    global log
    log = logging.getLogger(OCF_RESOURCE_INSTANCE)
    if int(OCF_RESKEY_debug) >= 1 or HA_DEBUG != "0":
        log.setLevel(logging.DEBUG)
    else:
        log.setLevel(logging.INFO)

    formater = logging.Formatter("(%(name)s) %(levelname)s: %(message)s")

    handler = logging.StreamHandler(stream=sys.stderr)
    handler.setFormatter(formater)
    log.addHandler(handler)

    if HA_LOGFACILITY:
        handler = logging.handlers.SysLogHandler("/dev/log")
        handler.setFormatter(formater)
        log.addHandler(handler)

    if HA_LOGFILE:
        handler = logging.FileHandler(HA_LOGFILE)
        handler.setFormatter(formater)
        log.addHandler(handler)

    if HA_DEBUGLOG and HA_DEBUGLOG != HA_LOGFILE:
        handler = logging.FileHandler(HA_DEBUGLOG)
        handler.setFormatter(formater)
        log.addHandler(handler)

def is_writable(_file):
    return os.access(_file, os.W_OK)

def is_executable_file(_file):
    return os.path.isfile(_file) and os.access(_file, os.X_OK)

def is_true(var):
    return re.match("yes|true|1|YES|TRUE|True|ja|on|ON", str(var)) != None

# Check if the binary exists and is executable
def check_binary(binary):
    if is_executable_file(binary):
        return True
    PATH = os.getenv("PATH", os.defpath)
    for _dir in PATH.split(os.pathsep):
        if is_executable_file(os.path.join(_dir, binary)):
            return True
    log.error("binary \"%s\" doesn't exist or not executable" % binary)
    return False

def run_command(commandline, shell=True):
    proc = subprocess.Popen(commandline, shell=shell, stdout=subprocess.PIPE,
                          stderr=subprocess.STDOUT, universal_newlines=True)
    stdout, stderr = proc.communicate()
    if proc.returncode != 0:
        log.error("command \"%s\" failed with code %s:\n%s" \
                    % (commandline, proc.returncode, stdout))
        raise Error()

# Functions for setting and getting the master score to tell Pacemaker which
# host has the most recent data
def set_master_score(score):
    if score == 0:
        run_command("crm_master -q -l forever -D")
    else:
        run_command("crm_master -q -l forever -v %s" % score)

def set_remote_master_score(remote, score):
    if score == 0:
        run_command("crm_master -q -l forever -N '%s' -D" % remote)
    else:
        run_command("crm_master -q -l forever -N '%s' -v %s" % (remote, score))

def get_master_score():
    proc = subprocess.Popen("crm_master -q -G", shell=True,
                            stdout=subprocess.PIPE, stderr=subprocess.DEVNULL,
                            universal_newlines=True)
    stdout, stderr = proc.communicate()
    if proc.returncode != 0:
        return 0
    else:
        return int(str.strip(stdout))

def get_remote_master_score(remote):
    proc = subprocess.Popen("crm_master -q -N '%s' -G" % remote, shell=True,
                            stdout=subprocess.PIPE, stderr=subprocess.DEVNULL,
                            universal_newlines=True)
    stdout, stderr = proc.communicate()
    if proc.returncode != 0:
        return 0
    else:
        return int(str.strip(stdout))

# Tell Pacemaker that the remote resource failed
def report_remote_failure(remote):
    try:
        run_command("crm_resource --resource '%s' --fail --node '%s'"
                    % (OCF_RESOURCE_INSTANCE, remote))
    except Exception as e:
        log.error(str(e));

def recv_line(fd):
    line = b''
    while True:
        tmp = fd.recv(1)
        line += tmp
        if tmp == b'\n' or len(tmp) == 0:
            break
    return line.decode()

def read_answer(fd):
    line = recv_line(fd)

    if len(line) == 0:
        log.error("qmp connection closed")
        raise Error()

    return json.loads(line)

# Execute one or more qmp commands
def qmp_execute(fd, commands, ignore_error = False):
    for command in commands:
        if not command:
            continue

        to_send = json.dumps(command)
        fd.sendall(str.encode(to_send + "\n"))

        answer = read_answer(fd)

        if not ignore_error and ("error" in answer):
            log.error("qmp command returned error:\n%s\n%s" \
                        % (json.dumps(command), json.dumps(answer)))
            raise Error()

    return answer

def get_timeout():
    return OCF_RESKEY_CRM_meta_timeout/1000 - 5

# Open qemu qmp connection
def qmp_open():
    try:
        fd = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
        fd.settimeout(get_timeout())
        fd.connect(HELPER_SOCK)
    except socket.error as e:
        log.error("while connecting to helper socket: %s" % e)
        raise Error()

    return fd

def qmp_query_status(fd):
    return qmp_execute(fd, [{"exec-colod": "query-status"}])["return"]

def qmp_query_store(fd):
    return qmp_execute(fd, [{"exec-colod": "query-store"}])["return"]

def qmp_query_peer(fd):
    return qmp_execute(fd, [{"exec-colod": "query-peer"}])["return"]["peer"]

def qmp_update_store(fd, update):
    store = qmp_query_store(fd)
    store.update(update)
    qmp_execute(fd, [{"exec-colod": "set-store", "store": store}])

def get_pid(pidfile):
    if not os.path.exists(pidfile):
        return None

    with open(pidfile, "r") as fd:
        pid = int(str.strip(fd.readline()))

    return pid

def pid_running(pidfile):
    if not os.path.exists(pidfile):
        return False

    pid = get_pid(pidfile)
    try:
        os.kill(pid, 0)
    except OSError:
        return False
    else:
        return True

def new_peer(fd, peer):
    if qmp_query_peer(fd):
        return

    qmp_execute(fd, [{"exec-colod": "set-peer", "peer": peer}])
    qmp_execute(fd, [{"exec-colod": "start-migration"}])
    # The secondary has inconsistent data until resync is finished
    set_remote_master_score(peer, 0)

def del_peer(fd):
    qmp_execute(fd, [{"exec-colod": "clear-peer"}])

def qemu_colo_monitor():
    running = pid_running(COLOD_PIDFILE)
    if not running:
        return OCF_NOT_RUNNING

    fd = qmp_open()

    status = qmp_query_status(fd)
    if status["failed"]:
        log.error("qemu failed: %s" % status)
        return OCF_ERR_GENERIC

    if OCF_RESKEY_CRM_meta_interval != 0:
        if not status["primary"] and status["replication"]:
            if get_master_score() < 100:
                set_master_score(100)

    pretend_secondary = qmp_query_store(fd)["pretend-secondary"]
    fd.close()

    if status["primary"] and not pretend_secondary:
        return OCF_RUNNING_MASTER
    else:
        return OCF_SUCCESS

def qemu_colo_start():
    if pid_running(COLOD_PIDFILE):
        log.info("qemu is already running")
        return OCF_SUCCESS

    try:
        os.mkdir(BASE_DIR)
    except FileExistsError as e:
        pass

    try:
        run_command(colod_cmdline(), shell=False)
    except Error as e:
        if os.access(BASE_DIR + "/colod.log", os.F_OK):
            with open(BASE_DIR + "/colod.log", "r") as fd:
                log.error(fd.read())
        raise e

    fd = qmp_open()
    qmp_update_store(fd, {"pretend-secondary": True})
    qmp_execute(fd, [ {"exec-colod": "demote"} ])

    if qmp_query_status(fd)["failed"]:
        qmp_execute(fd, [ {"exec-colod": "quit"} ])
        return OCF_ERR_GENERIC

    fd.close()

    return OCF_SUCCESS

def env_do_shutdown_guest():
    return OCF_RESKEY_CRM_meta_notify_active_uname \
           and OCF_RESKEY_CRM_meta_notify_stop_uname \
           and str.strip(OCF_RESKEY_CRM_meta_notify_active_uname) \
               == str.strip(OCF_RESKEY_CRM_meta_notify_stop_uname)

def env_find_secondary():
    # slave(s) =
    # OCF_RESKEY_CRM_meta_notify_slave_uname
    # - OCF_RESKEY_CRM_meta_notify_stop_uname
    # + OCF_RESKEY_CRM_meta_notify_start_uname
    # Filter out hosts that are stopping and ourselves
    for host in str.split(OCF_RESKEY_CRM_meta_notify_slave_uname, " "):
        if host:
            for stopping_host \
                in str.split(OCF_RESKEY_CRM_meta_notify_stop_uname, " "):
                if host == stopping_host:
                    break
            else:
                if host != HOSTNAME:
                    # we found a valid secondary
                    return host

    for host in str.split(OCF_RESKEY_CRM_meta_notify_start_uname, " "):
        if host != HOSTNAME:
            # we found a valid secondary
            return host

    # we found no secondary
    return None

def calculate_master_score(status, shutdown_guest):
    primary = status["primary"]
    replication = status["replication"]
    failed = status["failed"]

    if shutdown_guest:
        if not primary and not replication:
            pass
        elif not primary and replication and not failed:
            set_master_score(10)
        elif not primary and replication and failed:
            set_master_score(0)
        elif primary and not replication:
            set_master_score(11)
        elif primary and replication and not failed:
            set_master_score(11)
        elif primary and replication and failed:
            set_master_score(0)
        else:
            raise Error()

    elif status["peer-failed"]:
        if not primary and not replication:
            pass
        elif not primary and replication:
            set_master_score(10)
        elif primary and not replication:
            set_master_score(11)
        elif primary and replication:
            set_master_score(11)
        else:
            raise Error()

    else:
        if not primary and not replication:
            pass
        elif not primary and replication:
            set_master_score(0)
        elif primary and not replication:
            set_master_score(11)
        elif primary and replication:
            set_master_score(0)
        else:
            raise Error()

def maybe_shutdown(fd):
    shutdown_guest = env_do_shutdown_guest()
    status = qmp_query_status(fd)

    if shutdown_guest and not status["failed"]:
        try:
            qmp_execute(fd, [{"exec-colod": "shutdown"}])
        except Error:
            pass

def qemu_colo_stop():
    if not pid_running(COLOD_PIDFILE):
        log.info("resource is already stopped")
        return OCF_SUCCESS

    try:
        timeout = START_TIME + get_timeout()

        fd = qmp_open()
        status = qmp_query_status(fd)
        maybe_shutdown(fd)
        qmp_execute(fd, [{"exec-colod": "quit"}])
        fd.close()

        while pid_running(COLOD_PIDFILE):
            if time.time() >= timeout:
                raise Error()
            log.debug("Waiting for colod to stop")
            time.sleep(1)

        calculate_master_score(status, env_do_shutdown_guest())

    except Exception:
        log.info("force stopping colod")

        pid = get_pid(COLOD_PIDFILE)
        try:
            os.kill(pid, signal.SIGKILL)
        except Exception:
            pass

        while pid_running(COLOD_PIDFILE):
            log.debug("Waiting for colod to stop")
            time.sleep(1)

    return OCF_SUCCESS

def qemu_colo_notify():
    fd = qmp_open()
    status = qmp_query_status(fd)
    fd.close()

    if status["failed"]:
        return OCF_ERR_GENERIC

    action = "%s-%s" % (OCF_RESKEY_CRM_meta_notify_type, \
                        OCF_RESKEY_CRM_meta_notify_operation)

    if action == "post-start":
        if status["primary"]:
            peer = str.strip(OCF_RESKEY_CRM_meta_notify_start_uname)
            fd = qmp_open()
            new_peer(fd, peer)
            fd.close()

    elif action == "post-demote":
        if status["primary"]:
            peer = str.strip(OCF_RESKEY_CRM_meta_notify_demote_uname)
            fd = qmp_open()
            new_peer(fd, peer)
            fd.close()

    elif action == "pre-stop":
        if not env_do_shutdown_guest() \
           and (status["primary"] or status["replication"]) \
           and HOSTNAME != str.strip(OCF_RESKEY_CRM_meta_notify_stop_uname):
            peer = str.strip(OCF_RESKEY_CRM_meta_notify_stop_uname)
            fd = qmp_open()
            our_peer = qmp_query_peer(fd)
            log.debug("our peer: %s" % our_peer)
            if peer == our_peer:
                del_peer(fd)
            fd.close()

    elif action == "post-stop" \
         and OCF_RESKEY_CRM_meta_notify_key_operation == "stonith" \
         and (status["primary"] or status["replication"]):
        peer = str.strip(OCF_RESKEY_CRM_meta_notify_stop_uname)
        set_remote_master_score(peer, 0)
        fd = qmp_open()
        our_peer = qmp_query_peer(fd)
        log.debug("our peer: %s" % our_peer)
        if peer == our_peer:
            del_peer(fd)
        fd.close()

    return OCF_SUCCESS

def qemu_colo_promote():
    fd = qmp_open()
    status = qmp_query_status(fd)
    pretend_secondary = qmp_query_store(fd)["pretend-secondary"]
    fd.close()

    if status["failed"]:
        return OCF_ERR_GENERIC

    if not status["primary"] and not status["replication"]:
        fd = qmp_open()
        qmp_execute(fd, [{"exec-colod": "promote"}])

        if qmp_query_status(fd)["failed"]:
            return OCF_ERR_GENERIC

        qmp_update_store(fd, {"pretend-secondary": False})
        set_master_score(101)
        peer = env_find_secondary()
        if peer:
            new_peer(fd, peer)
        fd.close()

        return OCF_SUCCESS
    elif (status["primary"] or status["replication"]):
        fd = qmp_open()

        # Wait for promotion
        while not qmp_query_status(fd)["primary"]:
            log.debug("Waiting for promotion")
            time.sleep(1)

        qmp_update_store(fd, {"pretend-secondary": False})
        set_master_score(101)

        peer = env_find_secondary()
        if peer:
            new_peer(fd, peer)
        fd.close()
        return OCF_SUCCESS
    else:
        return OCF_ERR_GENERIC

def qemu_colo_demote():
    fd = qmp_open()
    status = qmp_query_status(fd)
    maybe_shutdown(fd)
    qmp_execute(fd, [{"exec-colod": "demote"}])
    calculate_master_score(status, env_do_shutdown_guest())

    if qmp_query_status(fd)["failed"]:
        return OCF_ERR_GENERIC

    fd.close()
    return OCF_SUCCESS

if OCF_ACTION == "meta-data":
    qemu_colo_meta_data()
    exit(OCF_SUCCESS)

logs_open()

status = qemu_colo_validate_all()
# Exit here if our sanity checks fail, but try to continue if we need to stop
if status != OCF_SUCCESS and OCF_ACTION != "stop":
    exit(status)

try:
    if OCF_ACTION == "start":
        status = qemu_colo_start()
    elif OCF_ACTION == "stop":
        status = qemu_colo_stop()
    elif OCF_ACTION == "monitor":
        status = qemu_colo_monitor()
    elif OCF_ACTION == "notify":
        status = qemu_colo_notify()
    elif OCF_ACTION == "promote":
        status = qemu_colo_promote()
    elif OCF_ACTION == "demote":
        status = qemu_colo_demote()
    elif OCF_ACTION == "validate-all":
        status = qemu_colo_validate_all()
    else:
        status = OCF_ERR_UNIMPLEMENTED
except Exception as e:
    log.error(str(e))
    log.error(traceback.format_exc())
    exit(OCF_ERR_GENERIC)
else:
    exit(status)
